###################################
#                                 #
#       UEconomy API config       #
#                                 #
###################################


#The time in minutes between baltop updates
#Set to -1 to update every time a player does /baltop (will lag most servers)
baltopUpdate: 5

#The time in days after an offline player's balance will be erased from the records
#Set to -1 to never remove their balance.
purgeDays: -1

#The maximum number of backup files to keep. Oldest backups will be deleted first
#Set to -1 or 0 to never delete backups. The minimum number of backups is 1.
numBackups: -1