main: jdz.UEconomy.UEco
name: UEco
version: 1.2
author: Jonodonozym
description: An economy plugin with a max balance of 1e308!
softdepend: [Vault]
depend: [JBU]

commands:
  about:
    description: displays information about the plugin
  balance:
    description: displays your current balance
    aliases: [bal]
  baltop:
    description: displays the richest players on the server
    aliases: [balancetop]
  pay:
    description: sends a specified amount to another player
    usage: /pay [player] [amount]
  ueco:
    descrption: Admin commands for UEconomy
    aliases: [ue, ueconomy]
    
permissions:
  ueco.admin:
    description: Gives access to all admin ueco commands
    default: op
  ueco.baltop:
    description: Gives access to the baltop command
    default: true
  ueco.pay:
    description: Gives access to the pay command
    default: false
    